language: php

sudo: required
addons:
  apt:
    packages:
      # - nginx
php:
  - 7.1
  - 7.2
  - 7.3
env:
  global:
    - COMPOSER_NO_INTERACTION=1

matrix:
  allow_failures:
  # - nightly
install:
  - composer install --prefer-dist --no-suggest

before_script:
    - cp ./example.env ./.env

script:
  - ./vendor/bin/phpunit
  - php lh create madeny.dev --a
  - cat ./cert/logs/log.sign