language: php

sudo: required
addons:
  apt:
    packages:
      # - nginx
php:
  - 7.1
  - 7.2
  - 7.3
  - 5.6
  # - nightly
env:
  global:
    - COMPOSER_NO_INTERACTION=1

matrix:
  allow_failures:
    - php: 5.6
install:
  - composer install --prefer-dist --no-suggest

before_script:
    - cp ./example.env ./.env
#   - composer self-update
#   - composer install  --no-interaction

script:
  - ./vendor/bin/phpunit
  - php lh create madeny.dev --a
  - cat ./cert/logs/log.sign